// Auto-generated — raw mesh names from Joints.glb
export const JOINT_MESH_NAMES = new Set([
  "Interosseous membrane of leg",
  "Anterior tibiofibular ligament",
  "Posterior tibiofibular ligament",
  "Transverse tibiofibular ligament",
  "Anterior talofibular ligament",
  "Calcaneofibular ligament",
  "Posterior talofibular ligament",
  "Posterior tibiotalar ligament",
  "Tibiocalcaneal ligament",
  "Tibionavicular ligament",
  "Acetabular labrum",
  "Articular capsule of hip joint",
  "Descending part of iliofemoral ligament",
  "Frenula capsulae",
  "Ischiofemoral ligament",
  "Ligament of head of femur",
  "Pubofemoral ligament",
  "Transverse acetabular ligament",
  "Transverse part of iliofemoral ligament",
  "Dorsal metatarsal ligaments",
  "Intersesamoid ligament",
  "Metatarsal interosseous ligaments",
  "Plantar metatarsal ligaments",
  "Articular capsule of interphalangeal joint of great toe",
  "Articular capsules of distal interphalangeal joints of foot",
  "Articular capsules of proximal interphalangeal joints of foot",
  "Collateral interphalangeal ligaments of foot",
  "Plantar interphalangeal ligaments",
  "Anterior talocalcaneal ligament",
  "Calcaneocuboid ligament",
  "Calcaneonavicular ligament",
  "Cuneocuboid interosseous ligament",
  "Dorsal calcaneocuboid ligament",
  "Dorsal cuboideonavicular ligament",
  "Dorsal cuneocuboid ligament",
  "Dorsal cuneonavicular ligaments",
  "Dorsal intercuneiform ligaments",
  "Intercuneiform interosseous ligaments",
  "Lateral talocalcaneal ligament",
  "Long plantar ligament",
  "Medial talocalcaneal ligament",
  "Plantar calcaneocuboid ligament",
  "Plantar cuneocuboid ligament",
  "Plantar cuneonavicular ligaments",
  "Plantar intercuneiform ligaments",
  "Posterior talocalcaneal ligament",
  "Plantar calcaneonavicular ligament",
  "Plantar cuboideonavicular ligament",
  "Talocalcaneal interosseous ligament",
  "Talonavicular ligament",
  "Articular capsules of metatarsophalangeal joints",
  "Collateral metatarsophalangeal ligaments",
  "Deep transverse metatarsal ligament",
  "Plantar metatarsophalangeal ligaments",
  "Cuneometatarsal interosseous ligaments",
  "Dorsal tarsometatarsal ligaments",
  "Plantar tarsometatarsal ligaments",
  "Anterior cruciate ligament",
  "Anterior meniscotibial ligament (Lateral meniscus)",
  "Anterior meniscotibial ligament (Medial meniscus)",
  "Arcuate popliteal ligament",
  "Articular capsule of knee joint",
  "Deep part of tibial collateral ligament",
  "Fibular collateral ligament",
  "Infrapatellar fat pad",
  "Lateral meniscus",
  "Medial meniscus",
  "Meniscopatellar ligament",
  "Oblique popliteal ligament",
  "Popliteofibular ligament",
  "Posterior cruciate ligament",
  "Posterior meniscotibial ligament (Lateral meniscus)",
  "Posterior meniscotibial ligament (Medial meniscus)",
  "Superficial part of tibial collateral ligament",
  "Transverse ligament of knee",
  "Anterior ligament of fibular head",
  "Articular capsule of superior tibiofibular joint",
  "Posterior ligament of fibular head",
  "Inferior pubic ligament",
  "Interpubic disc",
  "Superior pubic ligament",
  "Pubic symphysis",
  "Triradiate cartilage",
  "Iliolumbar ligament",
  "Obturator membrane",
  "Sacrospinous ligament",
  "Sacrotuberous ligament",
  "Anterior sacro-iliac ligament",
  "Interosseous sacro-iliac ligament",
  "Posterior sacro-iliac ligament",
  "Pterygospinous ligament",
  "Sphenomandibular ligament",
  "Stylohyoid ligament",
  "Stylomandibular ligament",
  "Articular capsule of temporomandibular joint",
  "Articular disc of temporomandibular joint",
  "Lateral temporomandibular ligament",
  "Interosseous membrane of forearm",
  "Oblique cord",
  "Articular disc of distal radio-ulnar joint",
  "Dorsal radio-ulnar ligament",
  "Palmar radio-ulnar ligament",
  "Annular ligament of radius",
  "Articular capsule of elbow joint",
  "Quadrate ligament",
  "Radial collateral ligament",
  "Ulnar collateral ligament",
  "Articular capsule of glenohumeral joint",
  "Coracohumeral ligament",
  "Glenoid labrum",
  "Inferior glenohumeral ligament",
  "Middle glenohumeral ligament",
  "Superior glenohumeral ligament",
  "Transverse humeral ligament",
  "Dorsal carpometacarpal ligaments",
  "Palmar carpometacarpal ligaments",
  "Capitohamate interosseous ligament",
  "Dorsal scaphotriquetral ligament",
  "Dorsal intercarpal ligaments",
  "Dorsal ulnocarpal ligament",
  "Lunotriquetral interosseous ligament",
  "Palmar capitohamate ligament",
  "Palmar lunotriquetral ligament",
  "Palmar scaphotriquetral ligament",
  "Palmar trapezoideocapitate ligament",
  "Pisohamate ligament",
  "Pisometacarpal ligament",
  "Pisotriquetral ligament",
  "Radial collateral ligament of wrist joint",
  "Radiate carpal ligament",
  "Scaphocapitate ligament",
  "Scaphotrapeziotrapezoidal ligament",
  "Scapholunate interosseous ligament",
  "Trapeziotrapezoidal interosseous ligament",
  "Trapezoideocapitate interosseous ligament",
  "Triquetrocapitate ligament",
  "Triquetrohamate ligament",
  "Ulnar collateral ligament of wrist joint",
  "Dorsal metacarpal ligaments",
  "Interosseous metacarpal ligaments",
  "Palmar metacarpal ligaments",
  "Articular capsules of distal interphalangeal joints",
  "Articular capsules of proximal interphalangeal joints",
  "Collateral interphalangeal ligaments of hand",
  "Palmar interphalangeal ligaments",
  "Articular capsules of metacarpophalangeal joints",
  "Collateral metacarpophalangeal ligaments",
  "Deep transverse metacarpal ligament",
  "Articular capsule of radiocarpal joint",
  "Dorsal radiocarpal ligament",
  "Radioscaphocapitate ligament",
  "Radiocapitate ligament",
  "Ulnocapitate ligament",
  "Ulnolunate ligament",
  "Ulnopisiform ligament",
  "Ulnotriquetral ligament",
  "Coraco-acromial ligament",
  "Inferior transverse scapular ligament",
  "Superior transverse scapular ligament",
  "Acromioclavicular ligament",
  "Articular capsule of acromioclavicular joint",
  "Articular disc of acromioclavicular joint",
  "Conoid ligament",
  "Trapezoid ligament",
  "Anterior sternoclavicular ligament",
  "Articular capsule of sternoclavicular joint",
  "Articular disc of sternoclavicular joint",
  "Costoclavicular ligament",
  "Interclavicular ligament",
  "Posterior sternoclavicular ligament",
  "Intervertebral disc C2-C3",
  "Intervertebral disc C3-C4",
  "Intervertebral disc C4-C5",
  "Intervertebral disc C5-C6",
  "Intervertebral disc C6-C7",
  "Intervertebral disc C7-T1",
  "Intervertebral disc L1-L2",
  "Intervertebral disc L2-L3",
  "Intervertebral disc L3-L4",
  "Intervertebral disc L4-L5",
  "Intervertebral disc L5-S1",
  "Intervertebral disc T1-T2",
  "Intervertebral disc T10-T11",
  "Intervertebral disc T11-T12",
  "Intervertebral disc T12-L1",
  "Intervertebral disc T2-T3",
  "Intervertebral disc T3-T4",
  "Intervertebral disc T4-T5",
  "Intervertebral disc T5-T6",
  "Intervertebral disc T6-T7",
  "Intervertebral disc T7-T8",
  "Intervertebral disc T8-T9",
  "Intervertebral disc T9-T10",
  "Nucleus pulposus C2-C3",
  "Nucleus pulposus C3-C4",
  "Nucleus pulposus C4-C5",
  "Nucleus pulposus C5-C6",
  "Nucleus pulposus C6-C7",
  "Nucleus pulposus C7-T1",
  "Nucleus pulposus L1-L2",
  "Nucleus pulposus L2-L3",
  "Nucleus pulposus L3-L4",
  "Nucleus pulposus L4-L5",
  "Nucleus pulposus L5-S1",
  "Nucleus pulposus T1-T2",
  "Nucleus pulposus T10-T11",
  "Nucleus pulposus T11-T12",
  "Nucleus pulposus T12-L1",
  "Nucleus pulposus T2-T3",
  "Nucleus pulposus T3-T4",
  "Nucleus pulposus T4-T5",
  "Nucleus pulposus T5-T6",
  "Nucleus pulposus T6-T7",
  "Nucleus pulposus T7-T8",
  "Nucleus pulposus T8-T9",
  "Nucleus pulposus T9-T10",
  "Sacrococcygeal symphysis",
  "Anterior longitudinal ligament",
  "Intercornual ligament",
  "Interspinous ligaments",
  "Ligamenta flava",
  "Nuchal ligament",
  "Posterior longitudinal ligament",
  "Supraspinous ligament",
  "Quadrangular membrane",
  "Median cricothyroid ligament",
  "Lateral thyrohyoid ligament",
  "Median thyrohyoid ligament",
  "Cricopharyngeal ligament",
  "External intercostal membrane",
  "Internal intercostal membrane",
  "Costotransverse ligament",
  "Intra-articular ligament of head of rib",
  "Radiate ligament of head of rib",
])
